import = ["~/.config/alacritty/themes/synthwave_84.toml",]



working_directory = "C:\\Users\\Dell\\"
[window]
padding = { x = 5, y = 5 }
dimensions = {columns = 150 , lines = 35}
position = {x = 45 , y = 50}
dynamic_padding = false
startup_mode = "Windowed"
opacity = 0.65


[font]
normal = { family = "FiraCode Nerd Font", style = "SemiBold" }
bold = { family = "FiraCode Nerd Font" }
italic = { family = "FiraCode Nerd Font", style = "italic" }
size = 12.0


[scrolling]
history = 10000
multiplier = 3


[shell]
program = "pwsh.exe"


[mouse]
hide_when_typing = true


[keyboard]
bindings = [
{key = "N" , mods = "Control|Shift" , action = "CreateNewWindow"},
]
#working_directory = "~/"
# args = ["--login"]
